language: python
python:
  - "3.9"
  -
os:
  - linux
  - osx

before_install:
  - pip install poetry pytest pytest-cov coveralls

install:
  - poetry install

script:
  - pytest --cov=onice_conversion --cov-report term-missing tests

after_script:
  - coveralls
