language: python
python:
  - "3.9"

os:
  - linux

addons:
  apt:
    packages:
      - libhdf5-dev

before_install:
  - pip install -U pip
  - pip install poetry pytest pytest-cov coveralls wheel

install:
  - poetry install

script:
  - pytest --cov=onice_conversion --cov-report term-missing tests

after_script:
  - coveralls
