[tool.poetry]
name = "onice_conversion"
version = "0.1.0"
description = "onice tools to convert lab-specific data to nwb"
authors = ["sneakers-the-rat <JLSaunders987@gmail.com>"]
license = "MPL-2.0"

[tool.poetry.dependencies]
python = "^3.9"
sphinx = {version = "^3.5.2", optional = true}
furo = {version = "^2021.2.28-beta.28", optional = true}

[tool.poetry.extras]
docs = ['sphinx', 'furo']

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
